# numpy
データをまとめて扱う：配列（arrayオブジェクト）

In [2]:
# numpyの配列
import numpy as np
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [3]:
a = np.array([[1, 2, 3], [4, 5, 6]])
a
a.shape  # どのような配列か確認する
a.ndim  # 配列が何次元か確かめる
a.dtype  # 配列の中身のデータ型を確認する
a.size  # 配列に合計いくつのデータが入っているか確認する

6

## さまざまな配列の作成
* arange関数
* zeros, ones
* linspace関数

In [4]:
np.arange(0, 30, 5)  # 0から30まで5とび

array([ 0,  5, 10, 15, 20, 25])

In [5]:
np.zeros((3, 4), dtype=np.int16)  # 0埋め配列
np.ones((3, 4), dtype=np.int16)  # 1埋め配列

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int16)

In [6]:
np.linspace(0, 2, 9)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [7]:
a = np.arange(6).reshape(2, 3)  # 配列の次元変換
a
a.T  # 行と列の入れ替え

array([[0, 3],
       [1, 4],
       [2, 5]])

## 配列の結合

In [8]:
x = np.arange(0, 10, 2)
y = np.arange(5)
z = np.arange(0, 100, 20)
print(x, y, z)

[0 2 4 6 8] [0 1 2 3 4] [ 0 20 40 60 80]


In [9]:
np.append(x, y)  # 2つの配列を1つにまとめる

array([0, 2, 4, 6, 8, 0, 1, 2, 3, 4])

In [11]:
np.vstack([x, y, z])  # 垂直方向にまとめる（積み上げる）

array([[ 0,  2,  4,  6,  8],
       [ 0,  1,  2,  3,  4],
       [ 0, 20, 40, 60, 80]])

In [12]:
np.hstack([x, y, z])  # 水平方向にまとめる

array([ 0,  2,  4,  6,  8,  0,  1,  2,  3,  4,  0, 20, 40, 60, 80])

## 配列の演算

In [13]:
a = np.arange(10, 51, 10)
b = np.arange(1, 6)
print(a, b)

[10 20 30 40 50] [1 2 3 4 5]


In [14]:
a - b  # それぞれの要素で引き算

array([ 9, 18, 27, 36, 45])

In [15]:
a < 30  # 比較演算子

array([ True,  True, False, False, False])

In [18]:
a = np.random.random((2,3))  # ランダムな数値で2行3列の配列を作成
a

array([[0.52520499, 0.80549016, 0.42160794],
       [0.62247758, 0.02566785, 0.03164285]])

In [22]:
a = np.arange(1,11)
print(
    a.sum(),
    a.mean(),
    a.max(),
    a.min()
)

55 5.5 10 1


In [25]:
a = np.arange(1, 11).reshape(2, 5)
print(a)
print(a.sum(axis=0))  # 0:行の合計
print(a.sum(axis=1))  # 1:列の合計
# axis（アクシス）：軸

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[ 7  9 11 13 15]
[15 40]
